/**
 * Seed 10 stock listings for testing.
 * Run from repo root: npm run seed-stock-listings
 * Requires .env with DATABASE_URL.
 */

import "dotenv/config";
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const LISTINGS = [
  {
    stockId: "Z00000001",
    status: "Available",
    fobPrice: 1250000,
    brand: "Toyota",
    model: "Camry",
    grade: "G",
    year: 2020,
    mileage: 45000,
    mileageVerified: true,
    transmission: "Automatic",
    extColor: "White",
    fuel: "Petrol",
    drive: "FWD",
    doors: 4,
    engine: "2500cc",
    score: "4.5",
    equipment: "Sunroof, Power Steering, Power Windows, Airbag, Leather Seats",
    seoTitle: "2020 Toyota Camry | Import from Japan | www.zervtek.com",
    metaDescription: "2020 Toyota Camry. Import directly from Japan with Zervtek. Quality used cars at competitive prices.",
    description: "Well-maintained 2020 Toyota Camry in excellent condition. Low mileage with verified history. Ideal for export.",
  },
  {
    stockId: "Z00000002",
    status: "Available",
    fobPrice: 980000,
    brand: "Honda",
    model: "Fit",
    grade: "RS",
    year: 2019,
    mileage: 62000,
    mileageVerified: false,
    transmission: "CVT",
    extColor: "Black",
    fuel: "Petrol",
    drive: "FWD",
    doors: 5,
    engine: "1300cc",
    score: "4.0",
    equipment: "Alloy Wheels, Power Steering, Power Windows, Airbag",
    seoTitle: "2019 Honda Fit RS - Japanese Used Cars | Zervtek",
    metaDescription: "Source your 2019 Honda Fit from Japan. Zervtek simplifies the import process.",
    description: "2019 Honda Fit RS with CVT. Compact and fuel-efficient, perfect for city driving.",
  },
  {
    stockId: "Z00000003",
    status: "Reserved",
    fobPrice: 2100000,
    brand: "Toyota",
    model: "Land Cruiser",
    grade: "VX",
    year: 2018,
    mileage: 78000,
    mileageVerified: true,
    transmission: "Automatic",
    extColor: "Silver",
    fuel: "Diesel",
    drive: "4WD",
    doors: 5,
    engine: "4500cc",
    score: "4.5",
    equipment: "Sunroof, Alloy Wheels, Power Steering, Power Windows, Airbag, Leather Seats",
    seoTitle: "2018 Toyota Land Cruiser VX | Import from Japan | www.zervtek.com",
    metaDescription: "2018 Toyota Land Cruiser available for export. Trust Zervtek for Japanese used car imports.",
    description: "Robust Land Cruiser VX with full service history. Mileage verified. Ready for export.",
  },
  {
    stockId: "Z00000004",
    status: "Available",
    fobPrice: 750000,
    brand: "Nissan",
    model: "Note",
    grade: "A",
    year: 2021,
    mileage: 28000,
    mileageVerified: true,
    transmission: "CVT",
    extColor: "Blue",
    fuel: "Hybrid",
    drive: "FWD",
    doors: 5,
    engine: "1500cc",
    score: "4.5",
    equipment: "Power Steering, Power Windows, Airbag",
    seoTitle: "2021 Nissan Note Hybrid | Import from Japan | www.zervtek.com",
    metaDescription: "Import 2021 Nissan Note Hybrid from Japan. Transparent pricing, verified vehicles.",
    description: "Low-mileage Nissan Note e-Power. Excellent fuel economy and reliability.",
  },
  {
    stockId: "Z00000005",
    status: "Available",
    fobPrice: 1650000,
    brand: "Mazda",
    model: "CX-5",
    grade: "Touring",
    year: 2019,
    mileage: 55000,
    mileageVerified: false,
    transmission: "Automatic",
    extColor: "Red",
    fuel: "Petrol",
    drive: "AWD",
    doors: 5,
    engine: "2000cc",
    score: "4.0",
    equipment: "Sunroof, Alloy Wheels, Power Steering, Power Windows, Airbag, Leather Seats",
    seoTitle: "2019 Mazda CX-5 Touring - Japanese Used Cars | Zervtek",
    metaDescription: "2019 Mazda CX-5 available for export. Trust Zervtek for Japanese used car imports.",
    description: "Mazda CX-5 in Soul Red. Well equipped with sunroof and leather. AWD for all conditions.",
  },
  {
    stockId: "Z00000006",
    status: "Available",
    fobPrice: 520000,
    brand: "Toyota",
    model: "Vitz",
    grade: "U",
    year: 2017,
    mileage: 95000,
    mileageVerified: false,
    transmission: "CVT",
    extColor: "Silver",
    fuel: "Petrol",
    drive: "FWD",
    doors: 5,
    engine: "1000cc",
    score: "3.5",
    equipment: "Power Steering, Power Windows, Airbag",
    seoTitle: "2017 Toyota Vitz | Import from Japan | www.zervtek.com",
    metaDescription: "2017 Toyota Vitz. Import from Japan with Zervtek. Affordable and reliable.",
    description: "Economical Toyota Vitz. High mileage but mechanically sound. Great value.",
  },
  {
    stockId: "Z00000007",
    status: "Sold",
    fobPrice: 1890000,
    brand: "Honda",
    model: "CR-V",
    grade: "Executive",
    year: 2020,
    mileage: 42000,
    mileageVerified: true,
    transmission: "CVT",
    extColor: "Black",
    fuel: "Petrol",
    drive: "AWD",
    doors: 5,
    engine: "1500cc",
    score: "4.5",
    equipment: "Sunroof, Alloy Wheels, Power Steering, Power Windows, Airbag, Leather Seats, Turbo",
    seoTitle: "2020 Honda CR-V Executive | Import from Japan | www.zervtek.com",
    metaDescription: "2020 Honda CR-V. Import directly from Japan with Zervtek.",
    description: "Top-spec CR-V with turbo engine. Mileage verified. Recently sold.",
  },
  {
    stockId: "Z00000008",
    status: "Available",
    fobPrice: 1100000,
    brand: "Subaru",
    model: "Forester",
    grade: "X",
    year: 2018,
    mileage: 67000,
    mileageVerified: true,
    transmission: "CVT",
    extColor: "Green",
    fuel: "Petrol",
    drive: "AWD",
    doors: 5,
    engine: "2500cc",
    score: "4.0",
    equipment: "Alloy Wheels, Power Steering, Power Windows, Airbag",
    seoTitle: "2018 Subaru Forester - Source from Japan | www.zervtek.com",
    metaDescription: "2018 Subaru Forester. Japanese used car export. Zervtek connects you with quality stock.",
    description: "Subaru Forester with symmetrical AWD. Ideal for all weather and light off-road.",
  },
  {
    stockId: "Z00000009",
    status: "Available",
    fobPrice: 680000,
    brand: "Daihatsu",
    model: "Tanto",
    grade: "X",
    year: 2022,
    mileage: 15000,
    mileageVerified: true,
    transmission: "CVT",
    extColor: "White",
    fuel: "Petrol",
    drive: "FWD",
    doors: 5,
    engine: "660cc",
    score: "5.0",
    equipment: "Power Steering, Power Windows, Airbag",
    seoTitle: "2022 Daihatsu Tanto | Import from Japan | www.zervtek.com",
    metaDescription: "2022 Daihatsu Tanto. Low mileage, verified. Visit www.zervtek.com.",
    description: "Nearly new Kei car. Very low mileage. Perfect for urban use or export.",
  },
  {
    stockId: "Z00000010",
    status: "Available",
    fobPrice: 1420000,
    brand: "Toyota",
    model: "Harrier",
    grade: "L",
    year: 2019,
    mileage: 48000,
    mileageVerified: false,
    transmission: "CVT",
    extColor: "Pearl White",
    fuel: "Hybrid",
    drive: "AWD",
    doors: 5,
    engine: "2500cc",
    score: "4.5",
    equipment: "Sunroof, Alloy Wheels, Power Steering, Power Windows, Airbag, Leather Seats",
    seoTitle: "2019 Toyota Harrier Hybrid | Import from Japan | www.zervtek.com",
    metaDescription: "2019 Toyota Harrier Hybrid. Import from Japan. Transparent pricing, verified vehicles.",
    description: "Luxury crossover with hybrid drivetrain. Comfortable and efficient. Popular export model.",
  },
];

async function main() {
  console.log("Seeding 10 stock listings...");
  for (const row of LISTINGS) {
    await prisma.stockListing.upsert({
      where: { stockId: row.stockId },
      create: {
        ...row,
        photoUrls: [],
        tag: "Stock Listing",
      },
      update: {
        status: row.status,
        fobPrice: row.fobPrice,
        brand: row.brand,
        model: row.model,
        grade: row.grade,
        year: row.year,
        mileage: row.mileage,
        mileageVerified: row.mileageVerified,
        transmission: row.transmission,
        extColor: row.extColor,
        fuel: row.fuel,
        drive: row.drive,
        doors: row.doors,
        engine: row.engine,
        score: row.score,
        equipment: row.equipment,
        seoTitle: row.seoTitle,
        metaDescription: row.metaDescription,
        description: row.description,
      },
    });
    console.log(`  ${row.stockId} – ${row.year} ${row.brand} ${row.model}`);
  }
  console.log("Done. 10 stock listings seeded.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
